### ISSUE TITLE
what is github prettifier?

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-prettifier#1]
# problem
- we use github issue tracker in a structured and complex way
  - issues have a hierarchy
  - labels are rules associated
- it's difficult to do this manually and make sure everything is well organized

# solution
- create a deamon that runs on a cronjob and/or github hooks that:
  - raises errors to signal broken rules
  - when possible, automatically fixes and enforces rules

# example of rules
- set of mandatory labels with correct colors
- subissue must link to parent, parent must list subissue with correct name and status
- issues with label discussion, documentation or containing subissues cannot have a PR
- ... ideas ?

# this issue is about..
Thinking about this tool at a high level, have a preliminary discussion. **Feel free to comment**

**Comment by lucacioria** [comment]
let's start the discussion @buildo/everyone  :)

**Comment by gabro** [comment]
:+1:
