### ISSUE TITLE
generate `sub-issues` paragraph

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/github-prettifier#10]
## requirements
automatically generate `sub-issues` paragraph on `macro` issues:

- check list of its sub issues
- if sub issue is closed -&gt; checked!

## specs

- get all issues (closed too!)
- filter sub issues: look for `&amp;amp;amp;amp;amp;lt;- #` in the body
- generate map with macro issues / sub issues (`{ [macroIssue]: [ subIssue, subIssue, ... ] }`)
 - `subIssue: { number, open, title }`
- for each macro issue generate `sub-issues` paragraph
 - title: `## sub-issues`
 - for each sub issue:
 - checkbox
 - id `issue.open === false` -&gt; checked!

## sub-issues

- [ ] fake sub-issue #12

**Comment by FrancescoCioria** [comment]
@lucacioria now this is some good specs! (proud of myself :sunglasses: )

**Comment by lucacioria** [comment]
I would add:
- remove epic from issue title (epic = `[epic name] issue title`)
- consider the backlink valid only if it's the first thing in the issue body

**Comment by FrancescoCioria** [comment]
Uff, I'll have to add a function `issuesWithBodyStartingWith` ok ok

**Comment by FrancescoCioria** [comment]
closing in favor of #15
