### ISSUE TITLE
remove "in review" and "wip" labels when PR is merged

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-prettifier#11]
Currently, the `in review` labels persists after the PR is merged. In this case the correct behavior is to only show the issue as closed, no labels are needed.

The result is neither useful nor pleasant at the moment:
![image](https://cloud.githubusercontent.com/assets/554092/12744206/3d5b40ba-c993-11e5-9009-070edaaedf4f.png)

**Comment by gabro** [comment]
Done in #16. Not retro-actively
