### ISSUE TITLE
Add macro label when processing sub-issues

### ISSUE THREAD

**Issue by gabro** [buildo/github-prettifier#17]
Use case: the first sub-issue is created -> a sub-issue section is added to the parent issue -> currently the macro label is not added. (It will be added as soon as the parent issue triggers a webhook)

**Comment by FrancescoCioria** [comment]
## specs
The return of `Rx`!
After most POSTs or PUTs our server will receive a new webhook. This is not true for title and comment edits --> If we generate an `Observable` stream of webhooks we can then manually push a `fakeWebhook` anytime we perform a POST or PUT which we know will not trigger another webhook from GitHub.
