### ISSUE TITLE
Automatically add web/api/iOS label based on the branch name

### ISSUE THREAD

**Issue by gabro** [buildo/github-prettifier#23]
## requirements
Whenever a PR is opened for a branch named `web-something`, add the `web` label to the PR (same thing for other subprojects, e.g. `api`, `ios`, `escalapio`)

## specs
Listen to the PR `opened` event, look at `pull_request.head.ref` string and add the matching label **if any**.
I would simply hard-code the 4 cases we need for now (`web`, `api`, `ios`, `escalapio`)

example of `ref` string
```
"action": "opened",
"pull_request": {
     ...
     "head": {
           "label": "buildo:web-1746-requestview_rightsidebar_testdetailresults",
           "ref": "web-1746-requestview_rightsidebar_testdetailresults",
           ...
     }
}
```

NB: we may have branches malformed (`"ref": "electron"`) or without a prefix (`"ref": "266-backgrounddimmer"`)

**Comment by giogonzo** [comment]
:+1: :+1: :+1:

**Comment by FrancescoCioria** [comment]
@gabro I improved the specs

**Comment by FrancescoCioria** [comment]
@gabro @giogonzo have a look at this issue: #8 

A couple of comments:
1. IMO we shouldn't fill the PR with useless labels, still the major topic (`iOS`, `web`...) can be useful to help pinpointing the PRs one may be interested in.

2. Should we also look at the associated issue and, if missing, add the topic label to it too?

**Comment by giogonzo** [comment]
> 1. IMO we shouldn't fill the PR with useless labels, still the major topic (iOS, web...) can be useful to help pinpointing the PRs one may be interested in.

the main topic is the only one I'm using

> 2. Should we also look at the associated issue and, if missing, add the topic label to it too?

+1, shouldn't hurt

**Comment by FrancescoCioria** [comment]
after #24 we're already adding any issue label to the PR.
Do you think we still need to add the topic label to the **issue** based on the branch of the PR?

PS: I'm adding the label "icebox" as I think we're already manually adding the topic label in the the vast majority --> not very useful for now

**Comment by gabro** [comment]
Closing for now
