### ISSUE TITLE
support both ← and <-

### ISSUE THREAD

**Issue by giogonzo** [buildo/github-prettifier#29]
comeon

**Comment by gabro** [comment]
use the damn sub-issue button and be done with it.

**Comment by giogonzo** [comment]
can't currently install it :(

**Comment by FrancescoCioria** [comment]
should we change this issue to support the unicodes?
`&larr;` `&#8592;` `&#x2190;` (they all render to ←)

**Comment by gabro** [comment]
for now, yes!
