### ISSUE TITLE
GET issue for pull_request sometimes fails

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/github-prettifier#34]
## description
from papertrail:
![image](https://cloud.githubusercontent.com/assets/4029499/13645383/118e81d6-e62b-11e5-9db7-dc44680fee1a.png)

(any other GET for that PR failed as well)

**Comment by FrancescoCioria** [comment]
@gabro any idea? that log comes from `octokat`

**Comment by FrancescoCioria** [comment]
actually it happened for other repos too:
![image](https://cloud.githubusercontent.com/assets/4029499/13645347/e197cf82-e62a-11e5-86f4-9572ecebab27.png)

**Comment by gabro** [comment]
that's odd... could it be that there's an extra trailing `/`, due to an `undefined` issue number?

**Comment by FrancescoCioria** [comment]
I'm going to check, but the GET should use the same number logged in the line above
(prettifier Updating labels of pull request #25 in repo hophop)
unless it's not the GET for the PR which is failing...

**Comment by FrancescoCioria** [comment]
Oh yeah, I'm stupid. This happens only for PR crated without `hophop` -> wrong title convention.
The search for the real bug (sub-issues task ignored) continues!
