### ISSUE TITLE
[reminders] remind to add "web/api/..." topic labels if missing

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/github-prettifier#47]
## requirements
some time after an issue is open, if it's missing one of the required labels (`web/api/escalapio/documentation`), @nemobot should make a comment to remind the creator of the issue to add one of those labels.

## specs
- create `processors/reminders.js` file
  - implement two tasks:
    -  `addReminderIfMissingTopicLabel`
      - input is GitHubEvent of a newly created issue --> if repo has at least one topic label and issue is missing a topic label launch fake event
    - `addMissingTopicLabelComment`
      - input is fake event --> GET issue --> if missing a topic label create comment and tag the creator of the issue
- topic labels:
  - `web`
  - `api`
  - `escalapio`
  - `documentation`
  - `iOS`
  - `QIA IS`
  - `QIA OD`

**Comment by gabro** [comment]
Other possible labels (if present): IOS, QIA IS, QIA OD

**Comment by FrancescoCioria** [comment]
@gabro what do you think: should we add `discussion` too or we can safely assume that any discussion is about one (or more) of those major topics?

**Comment by gabro** [comment]
I'd go with the second option and reconsider it in case some specific case pops up
