### ISSUE TITLE
enforce "macro" label

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-prettifier#5]
## requirements
- an issue has the label `macro` **if and only if** the issue description contains the string `## sub-issues`

## sub-issues

**Comment by FrancescoCioria** [comment]
should we check for other versions like `# sub-issues`, `## Sub-Issues`, `## sub issues` ?
@lucacioria

**Comment by lucacioria** [comment]
I would say not, as they will be enforced by the chrome extension..

I would probably prefer to have a separate prettifier task that changes those versions to the correct one, if people keep writing them
