### ISSUE TITLE
Sync Issue and PR labels

### ISSUE THREAD

**Issue by francescogior** [buildo/github-prettifier#8]
Issue and PR are 1-to-1 99% of the time and it'd be useful to have all the labels applied to the Issue reflected in the PR (and viceversa, or if easier, decide to never apply directly labels to the PR)

**Comment by FrancescoCioria** [comment]
>  it'd useful to have all the labels applied to the Issue reflected in the PRs

why not! (plus eventually the bot-only label `InReview` which is already being added)

**Comment by FrancescoCioria** [comment]
After thinking about it I say we should limit the labels for the PRs to just "WIP" and "InReview" as this is the only information we need when looking at `/pulls` (any other label would make it harder to notice the two labels)

/cc @buildo/everyone

**Comment by gabro** [comment]
Not sure I agree. Black labels are pretty visible anyway, and the other ones are nice to have in place, to provide extra context and filtering abilities (e.g. only `web` PRs)

<img width="1017" alt="screen shot 2016-03-03 at 5 51 03 pm" src="https://cloud.githubusercontent.com/assets/691940/13501844/8d3bc9a0-e168-11e5-84da-0153dc714090.png">

**Comment by giogonzo** [comment]
> this is the only information we need when looking at /pulls

not true for me, I keep adding the web label to every web PR to be able to filter on LOL

**Comment by giogonzo** [comment]
(so +1 for automating it)
