### ISSUE TITLE
Button with link to my issue of current milestone

### ISSUE THREAD

**Issue by francescogior** [buildo/github-prettifier#9]
I find myself very often using this keys combinations
- `G + I`
- `A + 'fr..'`
- ` M + 'thi...'`

to get https://github.omnilab.our.buildo.io/buildo/labonline/issues?q=is%3Aopen+is%3Aissue+assignee%3Afrancescogior+milestone%3A%22this+week%22

Bonus would be to have 2-3 buttons with link to the filter per label for 'starred' ones, say, 'WIP', 'IN REVIEW', 'BUG'...

**Comment by lucacioria** [comment]
@francescogior interesting proposal, but please move it to the repo github-workflow-pal (this repo is for the background worker, that one is for the extension, which can also change hotkeys if we want)

**Comment by francescogior** [comment]
:+1:

**Comment by francescogior** [comment]
Closing, moved here https://github.com/buildo/github-workflow-pal/issues/20
